# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
lune = "lune-org/lune@0.8.9"
Stylua = "JohnnyMorganz/Stylua@2.0.2"
pesde = "pesde-pkg/pesde@0.5.0-rc.16"
